spring.application.name: ingredients

logging:
  level.org.springframework.cloud: DEBUG

server.port: ${PORT:9994}

spring.rabbitmq.host: ${RABBIT_HOST:localhost}

logging.file: build/ingredients.log

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
spring.cloud.stream.binder.rabbit.default.maxConcurrency: 5