sudo: required
services:
  - docker

language: groovy

jdk:
- oraclejdk8

install:
- true

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx256m"

script: |
  cd ..
  ln -s brewery/acceptance-tests/scripts/runDockerAcceptanceTests.sh .
  bash -e runDockerAcceptanceTests.sh -t ZOOKEEPER

env:
  global:
  - TERM=dumb