sudo: required
dist: trusty
services:
  - docker

language: groovy

jdk:
- oraclejdk8

install:
- true

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"

script: |
  cd ..
  ln -s brewery/acceptance-tests/scripts/runDockerAcceptanceTests.sh .
  bash -e runDockerAcceptanceTests.sh -t SLEUTH -v 1.0.0.BUILD-SNAPSHOT
