sudo: required
services:
  - docker
  - rabbitmq

language: groovy

jdk:
- oraclejdk8

install:
- true

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx256m"

script:
- "bash -e runAcceptanceTests.sh -t ZOOKEEPER"

env:
  global:
  - TERM=dumb
  - SHOULD_START_RABBIT=no
  - RETRIES=200