language: groovy

jdk:
- oraclejdk8

install:
- true

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"

script:
- ./gradlew clean build --parallel -DWHAT_TO_TEST=SLEUTH
- bash -e scripts/runAcceptanceTests.sh -t SLEUTH -v 1.0.0.BUILD-SNAPSHOT
