aggregating:
  build: aggregating/build/docker
  environment:
    spring.profiles.active: eureka
  links:
    - discovery
  ports:
    - 9992:9992

maturing:
  build: maturing/build/docker
  environment:
    spring.profiles.active: eureka
  links:
    - discovery
  ports:
    - 9993:9993

bottling:
  build: bottling/build/docker
  environment:
    spring.profiles.active: eureka
  links:
    - discovery
  ports:
    - 9994:9994

presenting:
  build: presenting/build/docker
  environment:
    spring.profiles.active: eureka
  links:
    - discovery
  ports:
    - 9991:9991

zuul:
  build: zuul/build/docker
  environment:
    spring.profiles.active: eureka
  links:
    - discovery
  ports:
    - 9995:9995

ingredients:
  build: ingredients/build/docker
  environment:
    spring.profiles.active: eureka
  links:
    - discovery
  ports:
    - 9996:9996

configserver:
  build: config-server/build/docker
  environment:
    spring.profiles.active: eureka
  links:
    - discovery
  ports:
    - 8888:8888

discovery:
  build: eureka/build/docker
  ports:
    - 8761:8761

