brewing:
  build: brewing/build/docker
  links:
    - zookeeper:zk
    - rabbitmq
    - configserver
  environment:
      RABBIT_HOST: rabbitmq
      spring.cloud.config.uri: http://configserver:8888
  command: --spring.cloud.zookeeper.connectString=zk:2181
  ports:
    - 9992:9992
    - 8992:8992

presenting:
  build: presenting/build/docker
  links:
    - zookeeper:zk
    - rabbitmq
    - configserver
  environment:
      RABBIT_HOST: rabbitmq
      spring.cloud.config.uri: http://configserver:8888
  command: --spring.cloud.zookeeper.connectString=zk:2181
  ports:
    - 9991:9991
    - 8991:8991

zuul:
  build: zuul/build/docker
  links:
    - zookeeper:zk
    - rabbitmq
    - configserver
  environment:
      RABBIT_HOST: rabbitmq
      spring.cloud.config.uri: http://configserver:8888
  command: --spring.cloud.zookeeper.connectString=zk:2181
  ports:
    - 9993:9993
    - 8993:8993

configserver:
  build: config-server/build/docker
  ports:
    - 8888:8888

zookeeper:
  image: jplock/zookeeper
  expose:
    - 2181

rabbitmq:
  image: rabbitmq:management
  expose:
    - 5672
    - 15672

zipkin:
  build: zipkin-server/build/docker
  environment:
    - RABBIT_HOST=rabbitmq
    - zipkin.collector.sample-rate=1.0
    - zipkin.query.lookback=86400000
  ports:
    - 9411:9411
  links:
    - rabbitmq

web:
  image: openzipkin/zipkin-web:1.30.0
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=http
  ports:
    - 8080:8080
    - 9990:9990
  links:
    - zipkin:query
