web:
  image: openzipkin/zipkin-web:1.33.0
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=http
  ports:
    - 8080:8080
    - 9990:9990

rabbitmq:
  image: rabbitmq:management
  ports:
    - 9672:5672
    - 15672