brewing:
  build: brewing/build/docker
  environment:
    spring.profiles.active: consul
    spring.cloud.config.uri: http://configserver:8888
    RABBIT_HOST: rabbitmq
  links:
    - discovery
    - configserver
    - rabbitmq
  ports:
    - 9992:9992
    - 8992:8992

presenting:
  build: presenting/build/docker
  environment:
    spring.profiles.active: consul
    spring.cloud.config.uri: http://configserver:8888
    RABBIT_HOST: rabbitmq
  links:
    - discovery
    - configserver
    - rabbitmq
  ports:
    - 9991:9991
    - 8991:8991

zuul:
  build: zuul/build/docker
  environment:
    spring.profiles.active: consul
    spring.cloud.config.uri: http://configserver:8888
    RABBIT_HOST: rabbitmq
  links:
    - discovery
    - configserver
    - rabbitmq
  ports:
    - 9993:9993
    - 8993:8993

configserver:
  build: config-server/build/docker
  ports:
    - 8888:8888

discovery:
  image: progrium/consul
  command: -server -bootstrap
  ports:
    - 8400:8400
    - 8500:8500
    - 8600:8600

rabbitmq:
  image: rabbitmq:management
  expose:
    - 5672
    - 15672
