aggregating:
  build: aggregating/build/docker
  environment:
    spring.profiles.active: consul
  links:
    - discovery
  ports:
    - 9992:9992

maturing:
  build: maturing/build/docker
  environment:
    spring.profiles.active: consul
  links:
    - discovery
  ports:
    - 9993:9993

bottling:
  build: bottling/build/docker
  environment:
    spring.profiles.active: consul
  links:
    - discovery
  ports:
    - 9994:9994

presenting:
  build: presenting/build/docker
  environment:
    spring.profiles.active: consul
  links:
    - discovery
  ports:
    - 9991:9991

discovery:
  image: progrium/consul
  command: -server -bootstrap
  ports:
    - 8400:8400
    - 8500:8500
    - 8600:8600
