brewing:
  build: brewing/build/docker
  links:
    - zookeeper:zk
    - collector:ck
    - configserver
    - rabbitmq
  environment:
      RABBIT_HOST: rabbitmq
      spring.zipkin.host: ck
      spring.cloud.config.uri: http://configserver:8888
  command: --spring.cloud.zookeeper.connectString=zk:2181
  ports:
    - 9992:9992
    - 8992:8992

presenting:
  build: presenting/build/docker
  links:
    - zookeeper:zk
    - collector:ck
    - configserver
    - rabbitmq
  environment:
      RABBIT_HOST: rabbitmq
      spring.zipkin.host: ck
      spring.cloud.config.uri: http://configserver:8888
  command: --spring.cloud.zookeeper.connectString=zk:2181
  ports:
    - 9991:9991
    - 8991:8991

zuul:
  build: zuul/build/docker
  links:
    - zookeeper:zk
    - collector:ck
    - configserver
    - rabbitmq
  environment:
      RABBIT_HOST: rabbitmq
      spring.zipkin.host: ck
      spring.cloud.config.uri: http://configserver:8888
  command: --spring.cloud.zookeeper.connectString=zk:2181
  ports:
    - 9993:9993
    - 8993:8993

configserver:
  build: config-server/build/docker
  ports:
    - 8888:8888

zookeeper:
  image: jplock/zookeeper
  expose:
    - 2181

mysql:
  image: openzipkin/zipkin-mysql:1.25.0
  ports:
    - 3306:3306

query:
  image: openzipkin/zipkin-query:1.25.0
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=http
    - STORAGE_TYPE=mysql
  expose:
    - 9411
  ports:
    - 9411:9411
    - 9901:9901
  links:
    - mysql:storage

web:
  image: openzipkin/zipkin-web:1.25.0
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=http
  ports:
    - 8080:8080
    - 9990:9990
  links:
    - query

rabbitmq:
  image: rabbitmq:management
  expose:
    - 5672
    - 15672

