aggregating:
  build: aggregating/build/docker
  links:
    - zookeeper:zk
    - rabbitmq
  environment:
    - RABBIT_HOST=rabbitmq
  command: --spring.cloud.zookeeper.connectString=zk:2181 \
           --spring.zipkin.enabled=false
  ports:
    - 9992:9992

maturing:
  build: maturing/build/docker
  links:
    - zookeeper:zk
    - rabbitmq
  environment:
    - RABBIT_HOST=rabbitmq
  command: --spring.cloud.zookeeper.connectString=zk:2181 \
           --spring.zipkin.enabled=false
  ports:
    - 9993:9993

bottling:
  build: bottling/build/docker
  links:
    - zookeeper:zk
    - rabbitmq
  environment:
    - RABBIT_HOST=rabbitmq
  command: --spring.cloud.zookeeper.connectString=zk:2181 \
           --spring.zipkin.enabled=false
  ports:
    - 9994:9994

presenting:
  build: presenting/build/docker
  links:
    - zookeeper:zk
    - rabbitmq
  environment:
    - RABBIT_HOST=rabbitmq
  command: --spring.cloud.zookeeper.connectString=zk:2181 \
           --spring.zipkin.enabled=false
  ports:
    - 9991:9991

reporting:
  build: reporting/build/docker
  links:
    - zookeeper:zk
    - rabbitmq
  environment:
    - RABBIT_HOST=rabbitmq
  command: --spring.cloud.zookeeper.connectString=zk:2181 \
           --spring.zipkin.enabled=false
  ports:
    - 9997:9997
    - 8997:8997

zookeeper:
  image: jplock/zookeeper
  expose:
    - 2181

rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"
