aggregating:
  build: aggregating/build/docker
  environment:
    spring.profiles.active: consul
    spring.cloud.config.uri: http://configserver:8888
  links:
    - discovery
    - configserver
  ports:
    - 9992:9992

maturing:
  build: maturing/build/docker
  environment:
    spring.profiles.active: consul
    spring.cloud.config.uri: http://configserver:8888
  links:
    - discovery
    - configserver
  ports:
    - 9993:9993

bottling:
  build: bottling/build/docker
  environment:
    spring.profiles.active: consul
    spring.cloud.config.uri: http://configserver:8888
  links:
    - discovery
    - configserver
  ports:
    - 9994:9994

presenting:
  build: presenting/build/docker
  environment:
    spring.profiles.active: consul
    spring.cloud.config.uri: http://configserver:8888
  links:
    - discovery
    - configserver
  ports:
    - 9991:9991

configserver:
  build: config-server/build/docker
  ports:
    - 8888:8888

discovery:
  image: progrium/consul
  command: -server -bootstrap
  expose:
    - 8400
    - 8500
    - 8600