spring.application.name: uservices/maturing

spring.cloud.zookeeper:
  # prefix is not working ATM - it's not combining the uservices/${spring.application.name}
  #prefix: uservices/
  dependencies:
    presenting:
      path: uservices/presenting
    bottling:
      path: uservices/bottling