logging:
  pattern:
    level: '%clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %5p'
  level.org.springframework.cloud: DEBUG

logging.file: build/zuul.log

server.port: ${PORT:9993}

spring.rabbitmq.host: ${RABBIT_HOST:localhost}

# TODO: Not working?
#zuul.route.ingredients: /

zuul:
  ignoredPatterns: /health
  ignoredServices: '*'
  routes:
    brewing: /**

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000