logging:
  pattern:
    level: '%clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %5p'

logging.file: application.log

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
