spring.application.name: brewing

logging:
  level.org.springframework.cloud: DEBUG

server.port: ${PORT:9992}

spring.rabbitmq.host: ${RABBIT_HOST:localhost}

logging.file: build/brewing.log

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

spring.cloud.stream:
  binder.rabbit.default.maxConcurrency: 5
  events.destination: events
