spring.application.name: brewing

logging:
  pattern:
    console: '%clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %5p'
    file: '%clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %5p'

server:
  port: 9992

spring.rabbitmq.host: ${RABBIT_HOST:localhost}

logging.file: build/brewing.log

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
spring.cloud.stream.binder.rabbit.default.maxConcurrency: 5