spring.application.name: presenting

logging:
  level.org.springframework.cloud: DEBUG

server.port: ${PORT:9991}

spring.rabbitmq.host: ${RABBIT_HOST:localhost}
spring.sleuth.web.skipPattern: /api-docs.*|/autoconfig|/health|/configprops|/dump|/info|/metrics.*|/mappings|/trace|/swagger.*|.*\.png|.*\.css|.*\.js|.*\.html|/favicon.ico|/hystrix.stream|/feed/process/.*

logging.file: build/presenting.log

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000