spring.rabbitmq.addresses: ${vcap.services.brewery-rabbitmq.credentials.uri}
spring.cloud.zookeeper.connectString: ${vcap.services.brewery-discovery.credentials.uri}:2181

spring.datasource.initialize: false