spring:
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: ${DEFAULT_HEALTH_HOST:localhost}
          brokers: ${DEFAULT_HEALTH_HOST:localhost}
#          headers:
#            - X-B3-TraceId
#            - X-B3-SpanId
#            - X-B3-Sampled
#            - X-B3-ParentSpanId
#            - X-Span-Name
#            - X-Process-Id