spring.application.name: zipkin

server:
  port: 9411

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
  sleuth:
    enabled: false
zipkin:
  store:
    type: mem

logging.file: build/zipkin-server.log