spring.application.name: reporting

logging:
  level.org.springframework.cloud: DEBUG

server.port: ${PORT:9995}

spring.rabbitmq.host: ${RABBIT_HOST:localhost}

logging.file: build/reporting.log

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

spring.cloud.stream:
  binder.rabbit.default.maxConcurrency: 5