logging:
  pattern:
    console: '%clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %5p'
    file: '%clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %5p'

logging.file: build/config-server.log

server.port: ${PORT:8888}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/brewery-config.git

spring.zipkin.enabled: false