spring.application.name: bottling

logging:
  pattern:
    level: '%clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %5p'

server:
  port: 9994

spring.cloud.zookeeper.discovery.root: /pl
spring.rabbitmq.host: ${RABBIT_HOST:localhost}

logging.file: build/log/application.log